"""
state_schema.py
---------------
Defines the shared memory state for the LangGraph workflow.
Every agent reads from and writes to this central state dictionary.
"""

from typing import TypedDict, Optional, Dict, Any

class AgentState(TypedDict):
    """
    Central state container for the LangGraph multi-agent workflow.
    Data travels through every node in the graph, accumulating outputs.
    """
    
    # Stores the uploaded client meeting transcript
    transcript: str
    
    # Stores the output generated by the Task Agent (pain points, requirements, etc.)
    requirements: Optional[Dict[str, Any]]
    
    # Stores the final validated requirements after HITL #1
    approved_requirements: Optional[Dict[str, Any]]
    
    # Stores the output generated by the Planning Agent (tech stack, architecture, etc.)
    plan: Optional[Dict[str, Any]]
    
    # Stores the output generated by the Feasibility Agent (score, timeline, risks, etc.)
    feasibility: Optional[Dict[str, Any]]
    
    # Stores the final validated planning and feasibility output after HITL #2
    approved_plan: Optional[Dict[str, Any]]
    
    # Stores the final consolidated report generated by the Report Agent
    report: Optional[Dict[str, Any]]
    
    # Stores user feedback received during HITL actions such as Edit or Regenerate
    feedback: Optional[str]

    # Stores the HITL action chosen by the user: 'approve', 'edit', or 'regenerate'
    hitl_action: Optional[str]